"""Short-lived customer-agent conversation audit records.

The transcript contains sensitive patient content. Records therefore carry an
explicit expiry timestamp and are removed by MongoDB's TTL monitor. Audit
writes are deliberately best-effort: an observability failure must never stop
or delay the clinical intake flow.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pymongo.collection import Collection

from app.content_safety import scrub_internal_transcription_prompts
from app.observability.privacy import error_type


TTL_INDEX_NAME = "ttl_customer_agent_chat_history"
TYPED_INPUT_SOURCE = "typed"
VOICE_INPUT_SOURCE = "voice_transcription"


def build_pending_voice_input(
    *,
    transcript: str,
    transcription_id: str,
    audio_capture_id: str | None = None,
    audio_filename: str | None = None,
) -> dict[str, str]:
    """Build server-owned provenance for the next submitted transcription."""

    clean_transcript = str(transcript or "").strip()
    clean_transcription_id = str(transcription_id or "").strip()
    if not clean_transcript or not clean_transcription_id:
        raise ValueError("transcript and transcription_id are required")

    provenance = {
        "text": clean_transcript,
        "inputSource": VOICE_INPUT_SOURCE,
        "transcriptionId": clean_transcription_id,
    }
    if audio_capture_id:
        provenance["audioCaptureId"] = str(audio_capture_id).strip()
    if audio_filename:
        # Store only a basename generated by the server, never a client path.
        provenance["audioFilename"] = str(audio_filename).rsplit("/", 1)[-1]
    return provenance


def resolve_patient_input_provenance(
    *,
    content: str,
    payload: dict[str, Any],
    pending_voice_input: dict[str, Any] | None,
) -> dict[str, str]:
    """Identify typed versus voice input without trusting client file metadata.

    New clients correlate the submission with ``transcriptionId``. For existing
    clients, the first submission after a delivered transcript consumes the
    server-owned pending voice input. This also preserves voice attribution
    when the patient edits the transcript before sending. Capture IDs and
    filenames always come from server state, not from the WebSocket payload.
    """

    typed = {"inputSource": TYPED_INPUT_SOURCE}
    if not pending_voice_input:
        return typed

    submitted_id = str(payload.get("transcriptionId") or "").strip()
    pending_id = str(pending_voice_input.get("transcriptionId") or "").strip()
    # An explicit different ID is stale and must not claim the current capture.
    # With no ID (legacy frontend), pending state is single-use and belongs to
    # the next submission, even when that transcript was edited.
    if submitted_id and submitted_id != pending_id:
        return typed

    resolved = {
        "inputSource": VOICE_INPUT_SOURCE,
        "transcriptionId": pending_id,
    }
    for key in ("audioCaptureId", "audioFilename"):
        value = pending_voice_input.get(key)
        if value:
            resolved[key] = str(value)
    return resolved


def ensure_chat_history_indexes(collection: "Collection") -> None:
    """Create expiry and investigation indexes for the audit collection."""

    collection.create_index(
        [("expiresAt", 1)],
        name=TTL_INDEX_NAME,
        expireAfterSeconds=0,
    )
    collection.create_index(
        [("userId", 1), ("createdAt", 1)],
        name="chat_history_user_created_at",
    )
    collection.create_index(
        [("sessionId", 1), ("createdAt", 1)],
        name="chat_history_session_created_at",
    )
    collection.create_index(
        [("attemptId", 1), ("createdAt", 1)],
        name="chat_history_attempt_created_at",
        sparse=True,
    )


def build_chat_message_document(
    *,
    user_id: object,
    session_id: object,
    role: str,
    content: str,
    retention_days: int,
    form_id: object = None,
    attempt_id: object = None,
    interview_id: object = None,
    message_type: str = "text_message",
    phase: object = None,
    section: object = None,
    request_id: object = None,
    question_id: object = None,
    error_code: object = None,
    input_source: object = None,
    transcription_id: object = None,
    audio_capture_id: object = None,
    audio_filename: object = None,
    created_at: datetime | None = None,
) -> dict[str, Any]:
    """Build a bounded, queryable transcript record with deterministic expiry."""

    if role not in {"patient", "agent", "system"}:
        raise ValueError("role must be patient, agent, or system")
    if retention_days <= 0:
        raise ValueError("retention_days must be positive")
    if not str(user_id or "").strip():
        raise ValueError("user_id is required")
    if not str(session_id or "").strip():
        raise ValueError("session_id is required")

    clean_content, _ = scrub_internal_transcription_prompts(str(content or ""))
    clean_content = str(clean_content).strip()
    if not clean_content:
        raise ValueError("content cannot be empty")

    timestamp = created_at or datetime.now(timezone.utc)
    if timestamp.tzinfo is None:
        timestamp = timestamp.replace(tzinfo=timezone.utc)

    document: dict[str, Any] = {
        # Keep the application identifier as a string. It is stable across
        # legacy ObjectId/string user schemas and is never returned publicly.
        "userId": str(user_id).strip(),
        "sessionId": str(session_id or "").strip(),
        "role": role,
        "content": clean_content,
        "messageType": str(message_type or "text_message"),
        "createdAt": timestamp,
        "expiresAt": timestamp + timedelta(days=retention_days),
    }
    optional_values = {
        "formId": form_id,
        "attemptId": attempt_id,
        "interviewId": interview_id,
        "phase": phase,
        "section": section,
        "requestId": request_id,
        "questionId": question_id,
        "errorCode": error_code,
        "inputSource": input_source,
        "transcriptionId": transcription_id,
        "audioCaptureId": audio_capture_id,
        "audioFilename": audio_filename,
    }
    for key, value in optional_values.items():
        if value is not None and str(value).strip():
            document[key] = str(value).strip()
    return document


def record_chat_message(
    collection: "Collection | None",
    **message: Any,
) -> bool:
    """Best-effort insert; return False rather than breaking the patient flow."""

    if collection is None:
        return False
    try:
        collection.insert_one(build_chat_message_document(**message))
        return True
    except Exception as exc:
        # Never print the exception payload because it may contain patient text.
        print(f"[chat-history] Audit write failed: {error_type(exc)}")
        return False
